# Generated by Django 4.0.2 on 2022-03-25 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 9, 10, 2, 250351)),
        ),
    ]
