# Generated by Django 4.0.2 on 2022-03-25 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.TimeField(default=datetime.datetime(2022, 3, 25, 9, 11, 22, 951742)),
        ),
    ]
